export const questions = [
  {
    Question: "What is the capital of France?",
    Subject: "History",
    Topic: "European Capitals",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Who discovered the electron?",
    Subject: "Physics",
    Topic: "Atomic Structure",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is the chemical symbol for gold?",
    Subject: "Chemistry",
    Topic: "Periodic Table",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Solve the equation x^2 + 4x + 4 = 0",
    Subject: "Math",
    Topic: "Quadratic Equations",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is the powerhouse of the cell?",
    Subject: "Biology",
    Topic: "Cell Biology",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Who was the first president of the United States?",
    Subject: "History",
    Topic: "U.S. Presidents",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is the formula for sulfuric acid?",
    Subject: "Chemistry",
    Topic: "Chemical Formulas",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Calculate the area of a triangle with base 8 and height 12",
    Subject: "Math",
    Topic: "Geometry",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "Name the process by which plants make their own food",
    Subject: "Biology",
    Topic: "Photosynthesis",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "In which year did World War II end?",
    Subject: "History",
    Topic: "World War II",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is the formula for methane?",
    Subject: "Chemistry",
    Topic: "Organic Chemistry",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Solve the equation 3x - 7 = 14",
    Subject: "Math",
    Topic: "Linear Equations",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "Who proposed the theory of evolution by natural selection?",
    Subject: "Biology",
    Topic: "Evolution",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "What was the significance of the Magna Carta?",
    Subject: "History",
    Topic: "Medieval History",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "How many protons are there in a carbon atom?",
    Subject: "Chemistry",
    Topic: "Atomic Structure",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Find the derivative of y = 2x^2 + 3x + 1",
    Subject: "Math",
    Topic: "Calculus",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is the function of the ribosomes in a cell?",
    Subject: "Biology",
    Topic: "Cell Biology",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Who wrote 'Romeo and Juliet'?",
    Subject: "History",
    Topic: "Literature",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is the common name for ascorbic acid?",
    Subject: "Chemistry",
    Topic: "Vitamins",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Solve the system of equations: 2x + y = 5, 3x - 2y = 8",
    Subject: "Math",
    Topic: "Linear Algebra",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is the structure of DNA?",
    Subject: "Biology",
    Topic: "Genetics",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Who was the founder of the Ottoman Empire?",
    Subject: "History",
    Topic: "Empires",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "Name the gas responsible for the greenhouse effect",
    Subject: "Chemistry",
    Topic: "Environmental Chemistry",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Find the integral of ∫(2x + 1)dx",
    Subject: "Math",
    Topic: "Calculus",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is the structure of a virus?",
    Subject: "Biology",
    Topic: "Microbiology",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "What caused the Industrial Revolution?",
    Subject: "History",
    Topic: "Industrial Revolution",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question:
      "What is the pH of a solution with a hydrogen ion concentration of 1 x 10^-8 M?",
    Subject: "Chemistry",
    Topic: "Acids and Bases",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Solve the trigonometric equation: sin(x) = 0.5",
    Subject: "Math",
    Topic: "Trigonometry",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is a cell membrane primarily composed of?",
    Subject: "Biology",
    Topic: "Cell Biology",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Who was known as the 'Father of Computer Science'?",
    Subject: "History",
    Topic: "Computer Science Pioneers",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "Name the element with atomic number 17",
    Subject: "Chemistry",
    Topic: "Periodic Table",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "Evaluate the limit lim(x -> 0) (sin(x)/x)",
    Subject: "Math",
    Topic: "Calculus",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "What is the role of the mitochondria in a cell?",
    Subject: "Biology",
    Topic: "Cell Biology",
    Difficulty: "easy",
    Marks: 5,
  },
  {
    Question: "In which year did the American Civil War begin?",
    Subject: "History",
    Topic: "American Civil War",
    Difficulty: "medium",
    Marks: 10,
  },
  {
    Question: "Name the element used in fluorescent lights",
    Subject: "Chemistry",
    Topic: "Elements",
    Difficulty: "easy",
    Marks: 5,
  },

  {
    Question: "What is Newton's first law of motion?",
    Subject: "Physics",
    Topic: "Motion",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Define Avogadro's number.",
    Subject: "Chemistry",
    Topic: "Chemical Equations",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Solve the quadratic equation x^2 - 4x + 4 = 0.",
    Subject: "Math",
    Topic: "Quadratic Equations",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Explain the process of photosynthesis.",
    Subject: "Biology",
    Topic: "Photosynthesis",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Describe the causes and consequences of World War II.",
    Subject: "History",
    Topic: "World War II",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "What is the formula for calculating gravitational force?",
    Subject: "Physics",
    Topic: "Gravitation",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Balancing a redox reaction in an acidic solution.",
    Subject: "Chemistry",
    Topic: "Redox Reactions",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Integration of e^x with respect to x.",
    Subject: "Math",
    Topic: "Integration",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question:
      "Discuss the structure and function of the human respiratory system.",
    Subject: "Biology",
    Topic: "Respiratory System",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question:
      "Examine the impact of the Renaissance on European culture and society.",
    Subject: "History",
    Topic: "Renaissance",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Explain the concept of electric field.",
    Subject: "Physics",
    Topic: "Electricity",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Characteristics of noble gases.",
    Subject: "Chemistry",
    Topic: "Noble Gases",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Solving a system of linear equations with matrices.",
    Subject: "Math",
    Topic: "Matrices",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Cell division: Mitosis vs. Meiosis.",
    Subject: "Biology",
    Topic: "Cell Division",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Causes and consequences of the Industrial Revolution.",
    Subject: "History",
    Topic: "Industrial Revolution",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Explain the laws of reflection.",
    Subject: "Physics",
    Topic: "Optics",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Properties and uses of alkali metals.",
    Subject: "Chemistry",
    Topic: "Alkali Metals",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Solving a differential equation using separation of variables.",
    Subject: "Math",
    Topic: "Differential Equations",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Functioning of the human digestive system.",
    Subject: "Biology",
    Topic: "Digestive System",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Impact of the French Revolution on world history.",
    Subject: "History",
    Topic: "French Revolution",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Explain the concept of magnetic field.",
    Subject: "Physics",
    Topic: "Magnetism",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Chemical properties of halogens.",
    Subject: "Chemistry",
    Topic: "Halogens",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question:
      "Finding the limit of a function as x approaches a certain value.",
    Subject: "Math",
    Topic: "Limits",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Functions of different types of blood cells.",
    Subject: "Biology",
    Topic: "Blood Cells",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Causes and effects of the American Civil War.",
    Subject: "History",
    Topic: "American Civil War",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Explain the laws of thermodynamics.",
    Subject: "Physics",
    Topic: "Thermodynamics",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Characteristics and uses of transition metals.",
    Subject: "Chemistry",
    Topic: "Transition Metals",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Solving a definite integral.",
    Subject: "Math",
    Topic: "Definite Integrals",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Functions of the endocrine system in the human body.",
    Subject: "Biology",
    Topic: "Endocrine System",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Political and social consequences of the Cold War.",
    Subject: "History",
    Topic: "Cold War",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Explain the concept of wave-particle duality.",
    Subject: "Physics",
    Topic: "Quantum Mechanics",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Properties and uses of noble gases.",
    Subject: "Chemistry",
    Topic: "Noble Gases",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Solving a system of differential equations.",
    Subject: "Math",
    Topic: "Differential Equations",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Structure and function of plant cells.",
    Subject: "Biology",
    Topic: "Plant Cells",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Causes and outcomes of the Peloponnesian War.",
    Subject: "History",
    Topic: "Peloponnesian War",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Explain the concept of electric potential energy.",
    Subject: "Physics",
    Topic: "Electricity",
    Difficulty: "Hard",
    Marks: 15,
  },
  {
    Question: "Chemical bonding in covalent compounds.",
    Subject: "Chemistry",
    Topic: "Covalent Compounds",
    Difficulty: "Hard",
    Marks: 15,
  },
];
